In [263]:
import pandas as pd
from splinter import Browser
from bs4 import BeautifulSoup as bs
import smtplib
import requests

In [264]:
url='https://booknow.appointment-plus.com/b6l56ers/'
executable_path = {'executable_path':'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [265]:
browser.visit(url)

input_element = browser.find_by_name('loginname')   
input_element.fill('jmedias')

input_element = browser.find_by_name('password')   
input_element.fill('3ggR0ll$')

button_element = browser.find_by_value('Log In').click()

In [266]:
browser.find_by_name('e_id').click()
browser.find_by_value('4807').click()

browser.find_by_name('service_id').click()
browser.find_by_value('6453').click()

browser.find_by_id('cv-leftnav-item-calendar-available-id').click()

In [267]:
html = browser.html
soup = bs(html, "html.parser")

In [268]:
date_scheduled = soup.find_all('table', class_='appointment-list-style')

date_list =[]
for TDs in date_scheduled:
    innerDivs= TDs.find_all("td")
    for idiv in innerDivs:
            date_list.append(idiv.get_text(strip=True))

In [269]:
if browser.is_element_present_by_name('next'):
        browser.find_by_name('next').click()
        
        html = browser.html
        soup = bs(html, "html.parser")
        date_scheduled = soup.find_all('table', class_='appointment-list-style')
        
        for TDs in date_scheduled:
                innerDivs= TDs.find_all("td")
                for idiv in innerDivs:
                        date_list.append(idiv.get_text(strip=True))

In [270]:
df = pd.DataFrame(date_list)
  
day_date=df[df[0].str.contains(',', na=False)]
day_date = day_date.reset_index(drop=True)
day_date.rename(columns = {0:'Date'}, inplace=True)

In [271]:
time_slot=df[df[0].str.contains(':', na=False)]
time_slot = time_slot.reset_index(drop=True)
time_slot.rename(columns= {0:'Time'}, inplace=True)

In [272]:
court1df = day_date.join(time_slot)
court1df['Court Name'] = 'Court 1' 
court1df = court1df[['Court Name', 'Date', 'Time']]

In [273]:
browser.find_by_name('e_id').click()
browser.find_by_value('5311').click()

In [274]:
html = browser.html
soup = bs(html, "html.parser")

In [275]:
date_scheduled = soup.find_all('table', class_='appointment-list-style')

date_list =[]
for TDs in date_scheduled:
    innerDivs= TDs.find_all("td")
    for idiv in innerDivs:
            date_list.append(idiv.get_text(strip=True))

In [276]:
if browser.is_element_present_by_name('next'):
        browser.find_by_name('next').click()
        
        html = browser.html
        soup = bs(html, "html.parser")
        date_scheduled = soup.find_all('table', class_='appointment-list-style')
        
        for TDs in date_scheduled:
                innerDivs= TDs.find_all("td")
                for idiv in innerDivs:
                        date_list.append(idiv.get_text(strip=True))

In [277]:
df = pd.DataFrame(date_list)
  
day_date=df[df[0].str.contains(',', na=False)]
day_date = day_date.reset_index(drop=True)
day_date.rename(columns = {0:'Date'}, inplace=True)

In [278]:
time_slot=df[df[0].str.contains(':', na=False)]
time_slot = time_slot.reset_index(drop=True)
time_slot.rename(columns= {0:'Time'}, inplace=True)

In [279]:
court2df = day_date.join(time_slot)
court2df['Court Name'] = 'Court 2' 
court2df = court2df[['Court Name', 'Date', 'Time']]

In [292]:
courtsdf = pd.concat([court1df,court2df])
courtsdf = courtsdf.reset_index(drop=True)
courtsdf['time_obj'] = pd.to_datetime(courtsdf['Time'])
courtsdf['time_obj'] = pd.to_datetime(courtsdf['time_obj'],format='%H:%M').dt.time
courtsdf.sort_values(by='time_obj', inplace=True)
courtsdf

   Court Name                         Date     Time  time_obj
11    Court 2  Wednesday, December 7, 2022   7:00am  07:00:00
12    Court 2  Wednesday, December 7, 2022   7:30am  07:30:00
13    Court 2  Wednesday, December 7, 2022   8:00am  08:00:00
14    Court 2  Wednesday, December 7, 2022   8:30am  08:30:00
15    Court 2  Wednesday, December 7, 2022   9:00am  09:00:00
16    Court 2  Wednesday, December 7, 2022   9:30am  09:30:00
3     Court 1  Wednesday, December 7, 2022  10:30am  10:30:00
4     Court 1  Wednesday, December 7, 2022  11:00am  11:00:00
5     Court 1  Wednesday, December 7, 2022  11:30am  11:30:00
6     Court 1  Wednesday, December 7, 2022  12:00pm  12:00:00
7     Court 1  Wednesday, December 7, 2022  12:30pm  12:30:00
0     Court 1    Tuesday, December 6, 2022   1:00pm  13:00:00
8     Court 1  Wednesday, December 7, 2022   1:00pm  13:00:00
9     Court 2    Tuesday, December 6, 2022   1:00pm  13:00:00
1     Court 1    Tuesday, December 6, 2022   1:30pm  13:30:00
10    Court 2    Tuesday, December 6, 2022   1:30pm  13:30:00
17    Court 2  Wednesday, December 7, 2022   1:30pm  13:30:00
2     Court 1    Tuesday, December 6, 2022   2:00pm  14:00:00

In [293]:
filtered_dates = courtsdf[courtsdf['Date'].str.contains('Wednesday', na=False)]
filtered_dates = filtered_dates.reset_index(drop=True)

filtered_dates

   Court Name                         Date     Time  time_obj
0     Court 2  Wednesday, December 7, 2022   7:00am  07:00:00
1     Court 2  Wednesday, December 7, 2022   7:30am  07:30:00
2     Court 2  Wednesday, December 7, 2022   8:00am  08:00:00
3     Court 2  Wednesday, December 7, 2022   8:30am  08:30:00
4     Court 2  Wednesday, December 7, 2022   9:00am  09:00:00
5     Court 2  Wednesday, December 7, 2022   9:30am  09:30:00
6     Court 1  Wednesday, December 7, 2022  10:30am  10:30:00
7     Court 1  Wednesday, December 7, 2022  11:00am  11:00:00
8     Court 1  Wednesday, December 7, 2022  11:30am  11:30:00
9     Court 1  Wednesday, December 7, 2022  12:00pm  12:00:00
10    Court 1  Wednesday, December 7, 2022  12:30pm  12:30:00
11    Court 1  Wednesday, December 7, 2022   1:00pm  13:00:00
12    Court 2  Wednesday, December 7, 2022   1:30pm  13:30:00